
server:
  port: 8081

spring:
  # 配置 Srping data jpa
  jpa:
    # 指定是否在spring容器启动时 创建表，默认是false
    generate-ddl: true
    # 在控制台是否显示 sql语句 show-sql，默认false
    show-sql: true
    # 指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.216.144:3306/test?useUnicode=true&amp;characterEncoding=utf8
    username: chain
    password: xiangyanniqiu_82

  # 配置日志
  logging:
    pattern:
      console: level-%level %msg%n

    level:
      root: info
      org.hibernate: info
      # 在show-sql 为true时 显示SQL中的动态参数值
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      # 在show-sql 为true时 显示查询结果
      org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
      com.abc: debug
